---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-backup-tool
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
data:
  GRAFANA_URL: "http://35.184.40.61:3000"
  GRAFANA_TOKEN: "eyJrIjoiY1hoSU1MdG1DcUIzenJ5WE82bXhJUEVYMUp6OEZ0bWUiLCJuIjoiYmFja3VwIiwiaWQiOjF9"
  GRAFANA_ADMIN_ACCOUNT: "admin"
  GRAFANA_ADMIN_PASSWORD: "admin"
  RESTORE: "true"
  ARCHIVE_FILE: "202211290029.tar.gz"
  GCS_BUCKET_NAME: "varun-grafanabackup"
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/config/google-storage-creds.json"
---
# Run grafana-backup-tool daily and store backups in an S3
# compatible object storage such as minio
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
  labels:
    app: grafana-backup-tool
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        app: grafana-backup-tool
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: grafana-backup-tool
              image: "mydock21/grafana-backup-tool:backup"
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: grafana-backup-tool
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: google-storage-creds
