---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-backup-tool
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
data:
  GRAFANA_URL: "http://35.184.40.61:3000"
  GRAFANA_TOKEN: "eyJrIjoiY1hoSU1MdG1DcUIzenJ5WE82bXhJUEVYMUp6OEZ0bWUiLCJuIjoiYmFja3VwIiwiaWQiOjF9"
  GRAFANA_ADMIN_ACCOUNT: "admin"
  GRAFANA_ADMIN_PASSWORD: "admin"
  RESTORE: "true"
  ARCHIVE_FILE: "202211290029.tar.gz"
  GCS_BUCKET_NAME: "varun-grafanabackup"
  GOOGLE_APPLICATION_CREDENTIALS: "/etc/config/google-storage-creds.json"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentdconf
  namespace: grafana-backup-tool
data:
  fluent.conf: |
      <source>
        @type tail
        time_key time
        format json
        path /opt/grafana-backup-tool/logs/grafana-backup-tool.log
        pos_file /tmp/grafana-backup-tool.log.pos
        tag grafana-backup-tool
      </source>

      <match grafana-backup-tool>
        @type elasticsearch
        host 34.72.203.226
        port 9200
        user elastic
        password U3cl5s1oB4TpmbYs
        index_name fluentd.${tag}
        logstash_format true
        logstash_prefix grafana-backup-tool
        flush_interval 1s
      </match>
# Run grafana-backup-tool daily and store backups in an S3
# compatible object storage such as minio
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
  labels:
    app: grafana-backup-tool
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
      labels:
        app: grafana-backup-tool
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: grafana-backup-tool
              image: "mydock21/grafana-backup-tool:backup"
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: grafana-backup-tool
              volumeMounts:
              - name: config-volume
                mountPath: /etc/config
              - name: applog
                mountPath: /opt/grafana-backup-tool/logs
            - name: fluentd
              args:
              - |
                while ! test -f /opt/grafana-backup-tool/logs/done; do
                  echo "Waiting for the cronjob to finish..."
                  sleep5
                done
                echo "Cronjob finsihed, exiting"
                exit 0
              
              env:
              - name: FLUENT_UID
                value: root
              - name: FLUENT_CONF
                value: fluent.conf
              - name: FLEUNTD_ARGS
                value: -c /fluentd/etc/fluent.conf
              image: saravak/fluentd:elastic
              volumeMounts:
              - name: applog
                mountPath: /opt/grafana-backup-tool/logs

          volumes:
            - name: config-volume
              configMap:
                name: google-storage-creds
            - name: applog
              emptyDir: {}
            - name: fdconf
              configMap:
                name: fluentdconf
